### ISSUE TITLE
OM AJARIN DONG OM

### ISSUE THREAD

**Issue by X4D0** [AaRai27/Exypnos#1]

**Comment by AaRai27** [comment]
Ajarin naon

**Comment by X4D0** [comment]
2 org dimasukin ke 1 list

**Comment by AaRai27** [comment]
Pk line ae lah...ribet d gmail... wkwkwk

**Comment by X4D0** [comment]
lah ini masuk ke gmail? wkkw gw di reposit lu padahal

**Comment by AaRai27** [comment]
He eh semua github pasti ke email keknya
